name: go-testcoverage
author: vladopajic
description: go-testcoverage is tool which reports issues when test coverage of a file or package is below set threshold.
inputs:
  config:
    description: Path of configuration file.
    required: true
runs:
  using: docker
  image: docker://ghcr.io/vladopajic/go-testcoverage:v0.0.3
  args:
    - -config=${{ inputs.config }}
